# Generated by Django 5.1.4 on 2025-01-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaordenadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='marca',
            field=models.CharField(blank=True, db_column='marca_tiendaordenadores', max_length=100, null=True),
        ),
    ]
