# Generated by Django 5.1.2 on 2024-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaordenadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafica',
            name='procesadores_reverse',
            field=models.ManyToManyField(related_name='graficas', to='tiendaordenadores.procesador'),
        ),
    ]
