# Generated by Django 5.1.2 on 2024-11-03 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaordenadores', '0002_grafica_procesadores_reverse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grafica',
            name='procesadores_reverse',
        ),
        migrations.AddField(
            model_name='grafica',
            name='grafica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='procesadores_reverse', to='tiendaordenadores.procesador'),
            preserve_default=False,
        ),
    ]
