# Generated by Django 5.1.4 on 2025-01-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaordenadores', '0002_vendedor_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafica',
            name='grafica_procesadores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesadores_reverse', to='tiendaordenadores.procesador'),
        ),
    ]
