# Generated by Django 5.1.4 on 2025-01-20 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaordenadores', '0003_alter_grafica_grafica_procesadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesador',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
