# Generated by Django 5.1.2 on 2024-11-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaordenadores', '0003_remove_grafica_procesadores_reverse_grafica_grafica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grafica',
            old_name='grafica',
            new_name='grafica_procesadores',
        ),
    ]
