# Generated by Django 5.1.4 on 2025-02-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaordenadores', '0005_discodurohdd_user_fuentealimentacion_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitorgrafica',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monitorgrafica',
            name='modo_conexion',
            field=models.CharField(choices=[('HDMI', 'HDMI'), ('DisplayPort', 'DisplayPort'), ('VGA', 'VGA'), ('DVI', 'DVI')], default='HDMI', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='monitorgrafica',
            unique_together={('monitor', 'grafica', 'modo_conexion')},
        ),
    ]
