# Generated by Django 5.1.2 on 2024-12-11 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaordenadores', '0006_grafica_placabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafica',
            name='memoriavram',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='grafica',
            name='potenciacalculo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
