# Generated by Django 5.1.2 on 2024-12-11 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaordenadores', '0009_alter_grafica_memoriavram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesador',
            name='hilos',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(35000)]),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='nucleos',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
