# Generated by Django 5.1.4 on 2024-12-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaordenadores', '0011_alter_fuentealimentacion_vatios'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='procesadores/'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='familiaram',
            field=models.TextField(choices=[('DDR3', 'Formato DDR3'), ('DDR4', 'Formato DDR4'), ('DDR5', 'Formato DDR5')]),
        ),
    ]
